export const languageMappingsWithText: {[key: string]: string} = {
    c: "printf(\"🌠 {selectedSnippet}: %d\\n\", {selectedSnippet});",
    cpp: "cout << \"🌠 {selectedSnippet}: \" << {selectedSnippet};",
    go: "fmt.Println(\"🌠 {selectedSnippet}:\", {selectedSnippet})",
    java: "System.out.println(\"🌠 {selectedSnippet}: \" + {selectedSnippet});",
    javascript: "console.log('🌠 {selectedSnippet}: ', {selectedSnippet});",
    javascriptreact: "console.log('🌠 {selectedSnippet}: ', {selectedSnippet});",
    php: "echo '<pre>';\necho '🌠 ${selectedSnippet}: ';\nvar_dump(${selectedSnippet});\ndie;",
    ruby: "puts \"🌠 {selectedSnippet}: #\{{selectedSnippet}.pretty_inspect\}\"",
    python: "print(f\"🌠 {selectedSnippet}: {{selectedSnippet}}\")",
    typescript: "console.log('🌠 {selectedSnippet}: ', {selectedSnippet});",
    typescriptreact: "console.log('🌠 {selectedSnippet}: ', {selectedSnippet});",
    vue: "console.log('🌠 {selectedSnippet}: ', {selectedSnippet});",
    shellscript: "echo \"🌠 {selectedSnippet}: ${selectedSnippet}\"",
    rust: "println!(\"🌠 {selectedSnippet}: {:?}\", {selectedSnippet});",
};

export const languageMappingsWithoutText: {[key: string]: string} = {
    c: "printf(\"🌠 \\n\");",
    cpp: "cout << \"🌠 \";",
    go: "fmt.Println(\"🌠 \")",
    java: "System.out.println(\"🌠 \");",
    javascript: "console.log('🌠 ');",
    javascriptreact: "console.log('🌠 ');",
    php: "echo '<pre>';\necho '🌠 ';\nvar_dump();\ndie;",
    python: "print(f\"🌠 \")",
    ruby: "puts \"🌠 \"",
    typescript: "console.log('🌠 ');",
    typescriptreact: "console.log('🌠 ');",
    vue: "console.log('🌠 ');",
    shellscript: "echo \"🌠 \"",
    rust: "println!(\"🌠 \");",
};